language: cpp
dist: trusty
sudo: required

matrix:
    include:
        - os: linux
          compiler: gcc
          env: BUILD_TYPE=Debug VERBOSE=1
        - os: linux
          compiler: gcc
          env: BUILD_TYPE=Release VERBOSE=1
        - os: linux
          compiler: clang
          env: BUILD_TYPE=Debug VERBOSE=1
        - os: linux
          compiler: clang
          env: BUILD_TYPE=Release VERBOSE=1

install:
    - sudo apt-get install libzmq3-dev libzmq3

script: ./build.sh

notifications:
    email: false
